# Deployment Script for X Scraper (PowerShell)
# 
# This script sets up the production configuration on your server.
# Run this script on your live server (hesam.me) after pulling from GitHub.
#
# Usage:
#   .\deploy.ps1 -WorkerUrl "https://twitter-api-proxy.smah0085.workers.dev"

param(
    [string]$WorkerUrl = "https://twitter-api-proxy.smah0085.workers.dev"
)

Write-Host "🚀 Deploying X Scraper..." -ForegroundColor Green
Write-Host "📝 Worker URL: $WorkerUrl" -ForegroundColor Cyan

# Create worker-config.js from template
if (-not (Test-Path "worker-config.js")) {
    Write-Host "📄 Creating worker-config.js..." -ForegroundColor Yellow
    $content = @"
/**
 * Worker Configuration - PRODUCTION
 * 
 * ⚠️ This file is gitignored and should NOT be committed to Git.
 * This file is auto-generated by deploy.ps1
 */

// Your actual Cloudflare Worker URL
window.WORKER_URL_OVERRIDE = '$WorkerUrl';
"@
    $content | Out-File -FilePath "worker-config.js" -Encoding UTF8
    Write-Host "✅ Created worker-config.js" -ForegroundColor Green
} else {
    Write-Host "⚠️  worker-config.js already exists, updating..." -ForegroundColor Yellow
    $content = Get-Content "worker-config.js" -Raw
    $content = $content -replace "window.WORKER_URL_OVERRIDE = '.*';", "window.WORKER_URL_OVERRIDE = '$WorkerUrl';"
    $content | Out-File -FilePath "worker-config.js" -Encoding UTF8
    Write-Host "✅ Updated worker-config.js" -ForegroundColor Green
}

# Verify file was created
if (Test-Path "worker-config.js") {
    Write-Host "✅ Deployment complete!" -ForegroundColor Green
    Write-Host "📋 Next steps:" -ForegroundColor Cyan
    Write-Host "   1. Verify worker-config.js contains your Worker URL"
    Write-Host "   2. Test your site: https://hesam.me/x-scraper/"
    Write-Host "   3. Make sure Cloudflare Worker has ALLOWED_ORIGINS set"
} else {
    Write-Host "❌ Error: worker-config.js was not created" -ForegroundColor Red
    exit 1
}

