#!/bin/bash
#
# Deployment Script for X Scraper
# 
# This script sets up the production configuration on your server.
# Run this script on your live server (hesam.me) after pulling from GitHub.
#
# Usage:
#   bash deploy.sh https://twitter-api-proxy.smah0085.workers.dev
#

set -e

WORKER_URL="${1:-https://twitter-api-proxy.smah0085.workers.dev}"

echo "🚀 Deploying X Scraper..."
echo "📝 Worker URL: $WORKER_URL"

# Create worker-config.js from template
if [ ! -f "worker-config.js" ]; then
    echo "📄 Creating worker-config.js..."
    cat > worker-config.js << EOF
/**
 * Worker Configuration - PRODUCTION
 * 
 * ⚠️ This file is gitignored and should NOT be committed to Git.
 * This file is auto-generated by deploy.sh
 */

// Your actual Cloudflare Worker URL
window.WORKER_URL_OVERRIDE = '$WORKER_URL';
EOF
    echo "✅ Created worker-config.js"
else
    echo "⚠️  worker-config.js already exists, updating..."
    sed -i "s|window.WORKER_URL_OVERRIDE = '.*';|window.WORKER_URL_OVERRIDE = '$WORKER_URL';|" worker-config.js
    echo "✅ Updated worker-config.js"
fi

# Verify file was created
if [ -f "worker-config.js" ]; then
    echo "✅ Deployment complete!"
    echo "📋 Next steps:"
    echo "   1. Verify worker-config.js contains your Worker URL"
    echo "   2. Test your site: https://hesam.me/x-scraper/"
    echo "   3. Make sure Cloudflare Worker has ALLOWED_ORIGINS set"
else
    echo "❌ Error: worker-config.js was not created"
    exit 1
fi

