#!/usr/bin/env bash

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: bash deploy.sh https://YOUR_WORKER.subdomain.workers.dev" >&2
  exit 64
fi

WORKER_URL="$1"

# Basic validation: must be *.workers.dev
if [[ ! "$WORKER_URL" =~ ^https://[a-z0-9-]+\.workers\.dev/?$ ]]; then
  echo "Invalid Worker URL. Expected: https://<name>.workers.dev" >&2
  exit 64
fi

# Create or update the gitignored production override
if [[ -f worker-config.js ]]; then
  # portable sed in-place: BSD/macOS vs GNU
  if [[ "${OSTYPE:-}" == darwin* ]]; then
    sed -i '' "s|window.WORKER_URL_OVERRIDE = '.*';|window.WORKER_URL_OVERRIDE = '$WORKER_URL';|" worker-config.js
  else
    sed -i "s|window.WORKER_URL_OVERRIDE = '.*';|window.WORKER_URL_OVERRIDE = '$WORKER_URL';|" worker-config.js
  fi
else
  cat > worker-config.js <<EOF
// Auto-generated by deploy.sh; DO NOT COMMIT.
window.WORKER_URL_OVERRIDE = '$WORKER_URL';
EOF
fi

echo "✅ worker-config.js set to $WORKER_URL (gitignored)"

