param(
  [Parameter(Mandatory = $true)]
  [ValidatePattern('^https://[a-z0-9-]+\.workers\.dev/?$')]
  [string]$WorkerUrl
)

$Path = "worker-config.js"
$Content = @"
// Auto-generated by deploy.ps1; DO NOT COMMIT.
window.WORKER_URL_OVERRIDE = '$WorkerUrl';
"@

Set-Content -Encoding UTF8 -Path $Path -Value $Content
Write-Host "✅ worker-config.js set to $WorkerUrl (gitignored)"

